name = "AdventofCode"
uuid = "1250b849-1c23-4ff1-be95-db620b512630"
authors = ["Andreas Theodosiou <atheodosiou@protonmail.ch> and contributors"]
version = "1.0.0-DEV"

[deps]
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
